certification/urls.py
from django.urls import path
from certification.apps import CertificationConfig
from certification.views import CertificationCreateView, CertificationListView, CertificationDetailView, \
    CertificationDeleteView, CertificationUpdateView

app_name = CertificationConfig.name

urlpatterns = [
    path('create_certification/', CertificationCreateView.as_view(), name='create_certification'),
    path('', CertificationListView.as_view(), name='certification_list'),
    path('detail_certification/<int:pk>', CertificationDetailView.as_view(), name='detail_certification'),
    path('delete_certification/<int:pk>', CertificationDeleteView.as_view(), name='delete_certification'),
    path('update_certification/<int:pk>', CertificationUpdateView.as_view(), name='update_certification'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('certification.urls', namespace='certification')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import UserRegistrateView, UserPasswordResetView, UserProfileView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registrate/', UserRegistrateView.as_view(), name='registrate'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

certification/forms.py
from django import forms
from django.forms import BooleanField
from certification.models import Certification


TECH = (
        ('''1.1.  Котлы (паровые, в том числе котлы-бойлеры, а также автономные 
            пароперегреватели и экономайзеры; водогрейные и пароводогрейные;)
            энерготехнологические; котлы-утилизаторы; котлы передвижных
            и транспортабельных установок; паровые и жидкостные, работающие
            с высокотемпературными органическими и неорганическими
            теплоносителями (кроме воды и водяного пара); электрокотлы''', '1.1'),
        ('''1.2. Металлические конструкции для котельного оборудования''', '1.2'),
        ('''1.3. Сосуды, работающие под давлением пара, газов, жидкостей''', '1.3'),
        ('''1.4. Трубопроводы пара и горячей воды''', '1.4')
    # BQ_5 = '''1.5. Барокамеры''', '1.5'
    # GE_1 = '''2.1. Внутренние газопроводы''', '2.1'
    # GE_2 = '''2.2. Наружные газопроводы стальные''', '2.2'
    # GE_3 = '''2.3. Наружные газопроводы полиэтиленовые''', '2.3'
    # GE_4 = '''2.4. Детали и узлы, газовое оборудование''', '2.4'
    # LTE_1 = '''3.1. Грузоподъемные краны''', '3.1'
    # LTE_2 = '''3.2. Подъемники (вышки)''', '3.2'
    # LTE_3 = '''3.3. Дороги канатные, их агрегаты, механизмы и детали. Фуникулеры''', '3.3'
    # LTE_4 = '''3.4. Эскалаторы. Лифты. Платформы подъемные для инвалидов. Пассажирские конвейеры''', '3.4'
    # LTE_5 = '''3.5. Краны – трубоукладчики''', '3.5'
    # LTE_6 = '''3.6. Краны – манипуляторы''', '3.6'
    # LTE_7 = '''3.7. Тали, лебедки''', '3.7'
    # LTE_8 = '''3.8. Устройства грузозахватные. Цепи для подъемно-транспортного оборудования''', '3.8'
    # LTE_9 = '''3.9. Крановые пути''', '3.9'
    # ME_1 = '''4.1. Технические устройства для горнодобывающих и горнообогатительных производств
    #         и подземных объектов''', '4.1'
    # SBF_1 = '''5.1. Металлические конструкции пролётных строений, опор и пилонов стальных
    #         мостов при изготовлении в заводских условиях''', '5.1'
    # SBF_2 = '''5.2. Металлические конструкции пролётных строений, опор и пилонов стальных
    #         мостов при сборке, сварке и ремонте в монтажных условиях''', '5.2'
    # OGPE_1 = '''6.1. Нефтегазопромысловое и буровое оборудование''', '6.1'
    # OGPE_2 = '''6.2. Морские трубопроводы, объекты на шельфе (трубопроводы на платформах,
    #         а также сварные основания морских платформ)''', '6.2'
    # OGPE_3 = '''6.3. Промысловые газонефтепродуктопроводы''', '6.3'
    # OGPE_4 = '''6.4. Магистральные газопроводы''', '6.4'
    # OGPE_5 = '''6.5. Магистральные нефтепроводы и нефтепродуктопроводы.''', '6.5'
    # OGPE_6 = '''6.6. Резервуары для хранения нефти и нефтепродуктов''', '6.6'
    # OGPE_7 = '''6.7. Нефтегазопроводные трубы. Детали трубопроводов. Запорная
    #         арматура. Насосы, компрессоры''', '6.7'
    # OGPE_8 = '''6.8. Технологические трубопроводы в пределах УКПГ, КС; ЛДПС, НПС;
    #         СПХГ; ДКС; ГРС; УЗРГ; ПРГ и др., за исключением трубопроводов, обеспечивающих транспорт
    #         газа, нефти и нефтепродуктов; трубопроводы автоматизированных газонаполнительных
    #         компрессорных станций (АГНКС)''', '6.8'
    # MEF_1 = '''7.1. Доменное, коксовое, сталеплавильное оборудование''', '7.1'
    # MEF_2 = '''7.2. Технологическое оборудование и трубопроводы для черной и цветной металлургии''', '7.2'
    # MEF_3 = '''7.3. Технические устройства для производства черных и цветных
    #         металлов и сплавов на их основе''', '7.3'
    # ECPOREFHI_1 = '''8.1. Оборудование химических, нефтехимических,
    #         нефтеперерабатывающих производств, работающее под давлением до 16 МПа''', '8.1'
    # ECPOREFHI_2 = '''8.2. Оборудование химических, нефтехимических, нефтеперерабатывающих
    #         производств, работающее под давлением более 16 МПа''', '8.2'
    # ECPOREFHI_3 = '''8.3. Оборудование химических, нефтехимических,
    #         нефтеперерабатывающих производств, работающее под вакуумом.''', '8.3'
    # ECPOREFHI_4 = '''8.4. Резервуары для хранения взрывопожароопасных и токсичных веществ''', '8.4'
    # ECPOREFHI_5 = '''8.5. Изотермические хранилища''', '8.5'
    # ECPOREFHI_6 = '''8.6. Криогенное оборудование''', '8.6'
    # ECPOREFHI_7 = '''8.7. Оборудование аммиачных холодильных установок''', '8.7'
    # ECPOREFHI_8 = '''8.8. Печи, котлы-утилизаторы, энерготехнологические, ВОТ''', '8.8'
    # ECPOREFHI_9 = '''8.9. Компрессорное и насосное оборудование''', '8.9'
    # ECPOREFHI_10 = '''8.10. Центрифуги, сепараторы''', '8.10'
    # ECPOREFHI_11 = '''8.11. Цистерны, контейнеры (бочки), баллоны для взрывопожароопасных
    #         и токсичных веществ''', '8.11'
    # ECPOREFHI_12 = '''8.12. Технологические трубопроводы и детали трубопроводов''', '8.12'
    # ETDG_1 = '''9.1. Транспортные средства (цистерны, контейнеры), тара, упаковка, предназначенных
    #         для транспортирования опасных веществ (кроме перевозки сжиженных токсичных газов)''', '9.1'
    # ETDG_2 = '''9.2. Подъездные пути необщего пользования''', '9.2'
    # ESPVRM_1 = '''10.1. Воздуходувные машины (турбокомпрессоры воздушные, турбовоздуходувки)''', '10.1'
    # ESPVRM_2 = '''10.2. Вентиляторы (центробежные, радиальные, ВВД)''', '10.2'
    # ESPVRM_3 = '''10.3. Дробилки молотковые, вальцовые станки, энтолейторы''', '10.3'
    # BS_1 = '''11.1. Металлические строительные конструкции''', '11.1'
    # BS_2 = '''11.2. Бетонные и железобетонные конструкции, арматура, арматурные
    #         и закладные изделия железобетонных конструкций,''', '11.2'
    # BS_3 = '''11.3. Металлические трубопроводы''', '11.3'
    # BS_4 = '''11.4. Конструкции и трубопроводы из полимерных материалов''', '11.4'
)

class MixinStyleForm:
    """Класс примесь для стилизации форм продукта"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class CertificationForm(MixinStyleForm, forms.ModelForm):

    class Meta:
        model = Certification
        fields = '__all__'


class TechForm(forms.ModelForm):
    technical_devices = forms.MultipleChoiceField(choices=TECH)

    class Meta:
        model = Certification
        fields = ('technical_devices', )
        # forms.MultipleChoiceField(choices=TECH
    # #form.py
    # CHOICES = [('pi', 'PI'), ('ci', 'CI')]
    #
    # class ClassNameForm(forms.ModelForm):
    #     field_name = forms.MultipleChoiceField(choices=CHOICES)
    #
    #     class Meta:
    #         model = ClassName
    #         fields = ['field_name',]

    # class Meta:
    #     model = Certification
    #     fields = ('technical_devices', )

    # def tech(self):
    #     technical_devices = self.cleaned_data['technical_devices']
    #     technical_devices = ''.join(technical_devices)
    #     return technical_devices

#
# from django import forms
#
#
# class CountryForm(forms.Form):
#     OPTIONS = (
#         ("AUT", "Austria"),
#         ("DEU", "Germany"),
#         ("NLD", "Neitherlands"),
#     )
#     Countries = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
#                                           choices=OPTIONS)

certification/views.py
from django.shortcuts import render
from django.forms import inlineformset_factory
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse

from certification.forms import CertificationForm, TechForm
from certification.models import Certification


class CertificationCreateView(CreateView):
    model = Certification
    form_class = CertificationForm
    success_url = reverse_lazy('certification:certification_list')
    # permission_required = "catalog.add_product"

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class CertificationUpdateView(UpdateView):
    model = Certification
    form_class = CertificationForm
    success_url = reverse_lazy('certification:certification_list')

    def tech(request):
        if request.method == 'POST':
                form = TechForm(request.POST)
                if form.is_valid():
                    technical_devices = form.cleaned_data.get('technical_devices')

        else:
            form = TechForm

            return render('certification_detail.html', {'detail_certification': form})

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data(**kwargs)
    #     VersionFormset = inlineformset_factory(Certification, extra=1)
    #     if self.request.method == 'POST':
    #         context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
    #     else:
    #         context_data['formset'] = VersionFormset(instance=self.object)
    #     return context_data

    # def tech(request, pk):
    #     ins = Certification.objects.get(pk=pk)
    #
    #     form = TechForm(instance=ins)
    #     if request.method == 'POST':
    #         form = form(request.POST, instance=ins)
    #         if form.is_valid():
    #             form.save()

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    # def get_form_class(self):
    #     user = self.request.user
    #     if (user.has_perm("catalog.set_info_product") and user.has_perm("catalog.set_category_product") and
    #             user.has_perm("catalog.set_published_status")):
    #         return ProductModeratorForm
    #     if user == self.object.owner:
    #         return ProductForm
    #     raise PermissionDenied


class CertificationListView(ListView):
    model = Certification

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data


class CertificationDetailView(DetailView):
    model = Certification


class CertificationDeleteView(DeleteView):
    model = Certification
    success_url = reverse_lazy('certification:certification_list')


# def countries_view(request):
#     if request.method == 'POST':
#         form = CountryForm(request.POST)
#         if form.is_valid():
#             countries = form.cleaned_data.get('countries')
#             # do something with your results
#     else:
#         form = CountryForm
#
#     return render_to_response('render_country.html', {'form': form},
#                               context_instance=RequestContext(request))

# #model.py
# class ClassName(models.Model):
#     field_name = models.CharField(max_length=100)
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         if self.field_name:
#             self.field_name= eval(self.field_name)
#
#
#
# #form.py
# CHOICES = [('pi', 'PI'), ('ci', 'CI')]
#
# class ClassNameForm(forms.ModelForm):
#     field_name = forms.MultipleChoiceField(choices=CHOICES)
#
#     class Meta:
#         model = ClassName
#         fields = ['field_name',]
#
# #view.py
# def viewfunction(request, pk):
#     ins = ClassName.objects.get(pk=pk)
#
#     form = ClassNameForm(instance=ins)
#     if request.method == 'POST':
#         form = form (request.POST, instance=ins)
#         if form.is_valid():
#             form.save()
#             ...

certification/templates/certification/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>НК и НАКС</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<header data-bs-theme="dark">
    {% include 'certification/include/inc_menu.html' %}
</header>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Аттестация НК</h1>
    <p class="lead">В разработке инструкция по заполнению БД и работе с ней</p>
</div>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">&copy; 2025-{% now 'Y' %}</small>
        </div>
        <div class="col-4 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">БД удостоверений НК</a></li>
                <li><a class="text-muted" href="#">БД удостоверений НАКС</a></li>
                <li><a class="text-muted" href="#">БД удостоверений ДПО НК</a></li>
                <li><a class="text-muted" href="#">БД удостоверений ДПО НАКС</a></li>
                <li><a class="text-muted" href="#">Для бухгалтерии</a></li>

            </ul>
        </div>
        <div class="col-4 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">В разработке</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

certification/templates/certification/certification_confirm_delete.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Хотите удалить удостоверение "{{object.certification}}"?</p>
                <button type="submit" class="btn btn-block btn-danger">Подтвердить</button>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-block btn-warning">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

certification/templates/certification/certification_detail.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.certificate }}</h4>
        </div>
        <div class="card-body">
            <img src="" alt="preview " width="300" height="250"
                 class="d-inline-block align-text-top">
            <h2 class="card-title pricing-card-title">{{ object.method }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                <li>{{ object.type_certification }}</li>
                <li>{{ object.technical_devices }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

certification/templates/certification/certification_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

certification/templates/certification/certification_list.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'certification:create_certification' %}">
        Добавить удостоверение
    </a>
</div>
{% for object in object_list %}
<div class="col-6" xmlns="http://www.w3.org/1999/html">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <h2 class="card-title pricing-card-title">{{ object.first_name }}</h2>
            <div class="btn-group">
                <p class="d-inline-flex gap-1">
                    <a href="{% url 'certification:detail_certification' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Инфо
                    </a>
                    <a href="{% url 'certification:update_certification' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Обновить
                    </a>
                    {% if user.is_superuser%}
                    <a href="{% url 'certification:delete_certification' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </a>
                    {% endif %}
                    <a class="btn btn-lg btn-block btn-outline-primary">
                        1235
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}