certification/urls.py
from django.urls import path
from certification.apps import CertificationConfig
from certification.views import CertificationCreateView, CertificationListView, CertificationDetailView, \
    CertificationDeleteView, CertificationUpdateView

app_name = CertificationConfig.name

urlpatterns = [
    path('create_certification/', CertificationCreateView.as_view(), name='create_certification'),
    path('', CertificationListView.as_view(), name='certification_list'),
    path('detail_certification/<int:pk>', CertificationDetailView.as_view(), name='detail_certification'),
    path('delete_certification/<int:pk>', CertificationDeleteView.as_view(), name='delete_certification'),
    path('update_certification/<int:pk>', CertificationUpdateView.as_view(), name='update_certification'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('certification.urls', namespace='certification')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import UserRegistrateView, UserPasswordResetView, UserProfileView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registrate/', UserRegistrateView.as_view(), name='registrate'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {
    'blank': True,
    'null': True
}


class User(AbstractUser):
    username = None
    email = models.EmailField(
        unique=True,
        verbose_name="email",
        help_text="Формат почты user@mail.ru"
    )
    phone = models.CharField(
        max_length=30,
        verbose_name="телефон",
        help_text="Формат номера телефона 8 888 888 88 88",
        **NULLABLE
    )
    token = models.CharField(
        max_length=70,
        verbose_name="token",
        **NULLABLE
    )
    first_name = models.CharField(
        max_length=200,
        verbose_name='Имя',
        **NULLABLE
    )
    patronymic = models.CharField(
        max_length=200,
        verbose_name='Отчество',
        **NULLABLE
    )
    last_name = models.CharField(
        max_length=200,
        verbose_name='Фамилиля',
        **NULLABLE
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f"{self.email}"

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, UserChangeForm
from django import forms

from users.models import User


class StyleFormMixin:
    """Класс примесь для стилизации форм пользователей"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegistrateForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserPasswordResetForm(StyleFormMixin, PasswordResetForm):

    class Meta:
        model = User
        fields = ('email',)


class UserProfileForm(StyleFormMixin, UserChangeForm):
    """Форма для изменения информации о пользователе"""
    class Meta:
        model = User
        fields = ('phone', 'first_name', 'patronymic', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets
import string
import random

from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegistrateForm, UserPasswordResetForm, UserProfileForm
from users.models import User


class UserRegistrateView(CreateView):
    model = User
    form_class = UserRegistrateForm
    template_name = 'users/users_form.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(20)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}'
        send_mail(
            subject='Подтверждение почты пользователя',
            message=f'Данное сообщение получено автоматически\n'
                    f'Если это были не Вы выполните следующие действия:\n'
                    f'1. Смените пароль.\n'
                    f'2. Проверьте актуальность номера телефона.\n'
                    f'3. Обратитесь в поддержку\n'
                    f'Перейдите по ссылке для подверждения почты: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email,]
        )
        return super().form_valid(form)


class UserPasswordResetView(PasswordResetView):
    model = User
    form_class = UserPasswordResetForm
    template_name = 'users/password_reset.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """ Проверка существования пользователя и отправка нового пароля на почту """
        email = form.cleaned_data["email"]
        user = User.objects.get(email=email)
        if user:
            new_password = ''
            for item in range(10):
                new_password += ''.join([random.choice(string.ascii_letters + string.digits + string.punctuation)])
            user.set_password(new_password)
            user.is_active = True
            user.save()
            send_mail(
                subject='Восстановление пароля',
                message=f'Данное сообщение получено автоматически.\n'
                        f'По Вашему обращению был сгенерирован новый пароль.\n'
                        f'Ваш пароль: {new_password}',
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email, ]
            )
            return redirect(reverse('users:login'))


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

users/templates/users/login.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Вход в личный кабинет</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        Войти
                    </button>
                    <a href="{% url 'certification:certification_list' %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Вернуться на главную
                    </a>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:password_reset' %}"
                   class="btn btn-lg btn-block btn-outline-primary">
                    Забыли пароль?
                </a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Восстановление пароля</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                       Отправить пароль на почту
                    </button>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Профиль пользователя</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                       Сохранить
                    </button>
                    <a href="{% url 'certification:certification_list' %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Вернуться на главную
                    </a>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/users_form.html
{% extends 'certification/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Регистрация</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                       Зарегистрироваться
                    </button>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}